# Generated by Django 4.2 on 2023-04-24 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_city', models.CharField(max_length=20)),
                ('shop_state', models.CharField(max_length=20)),
                ('shop_zipcode', models.CharField(max_length=15)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('shop_name',),
            },
        ),
    ]
