# Generated by Django 4.2 on 2023-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_city', models.CharField(max_length=20)),
                ('shop_state', models.CharField(max_length=20)),
                ('shop_zipcode', models.CharField(max_length=15)),
                ('phone_num', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('shop_name',),
            },
        ),
    ]
