# Generated by Django 4.2 on 2023-05-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_users_app', '0002_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
