# Generated by Django 4.2 on 2023-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_users_app', '0003_retailer_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
