# Generated by Django 4.2 on 2023-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finish',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='frameprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wood',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
