# Generated by Django 4.2 on 2023-04-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0002_alter_finish_image_alter_frameprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_style', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('width_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='frameprofile',
            name='price',
        ),
        migrations.AddField(
            model_name='frameprofile',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frameprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.pricekey'),
        ),
    ]
