# Generated by Django 4.2 on 2023-04-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0003_pricekey_remove_frameprofile_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricekey',
            name='height_price',
        ),
    ]
