# Generated by Django 4.2 on 2023-04-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0004_remove_pricekey_height_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frameprofile',
            old_name='width',
            new_name='width_quarters',
        ),
    ]
