# Generated by Django 4.2 on 2023-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0005_rename_width_frameprofile_width_quarters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frameprofile',
            old_name='name',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='frameprofile',
            name='width_quarters',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
