# Generated by Django 4.2 on 2023-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0006_rename_name_frameprofile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wood',
            old_name='price',
            new_name='price_modifier',
        ),
        migrations.AlterField(
            model_name='wood',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='wood',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
