# Generated by Django 4.2 on 2023-05-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nw_users_app', '0001_initial'),
        ('nw_orders_app', '0008_rename_price_finish_price_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_users_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Spline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='wood',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('depth', models.IntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('notes', models.CharField(max_length=300)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.order')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.frameprofile')),
                ('spline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.spline')),
                ('wood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.wood')),
            ],
        ),
    ]
