# Generated by Django 4.2 on 2023-05-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0011_orderitem_frame_price_orderitem_price_ui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(default='2222-01-22'),
        ),
    ]
