# Generated by Django 4.2 on 2023-05-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0013_alter_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='finish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.finish'),
        ),
    ]
