# Generated by Django 4.2 on 2023-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0017_order_frame_total_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='frame_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
