# Generated by Django 4.2 on 2023-06-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0023_orderitem_corner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TopTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price_modifier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.gold')),
            ],
        ),
        migrations.CreateModel(
            name='SideTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price_modifier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.gold')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.bole'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.gold'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='side_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.sidetreatment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nw_orders_app.toptreatment'),
        ),
    ]
