# Generated by Django 4.2 on 2023-06-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_orders_app', '0024_bole_gold_toptreatment_sidetreatment_orderitem_bole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gold_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gold_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
